### ISSUE TITLE
发现代码中评估指标fMSE的计算方式不同

### ISSUE THREAD

**Issue by dorianzhang7** [bcmi/Video-Harmonization-Dataset-HYouTube#4]
作者您好 我在用代码evaluate_model.py对模型结果进行定量分析时，发现计算fMSE的方式和其他相关论文不同
本文代码截图如下：
![image](https://user-images.githubusercontent.com/103979308/194798930-21ebb349-e0b2-4a75-b808-9a015b65b43b.png)
还有一些代码中是采用mask乘积后的图像计算误差，如下：
![image](https://user-images.githubusercontent.com/103979308/194798941-325dec92-369c-42df-9743-07e5ecb390fe.png)
两种方式我分别评估了issam_final.pth模型的fMSE指标，会存在接近10点的差异，这篇论文的结果指标会更加好，如下图：
![image](https://user-images.githubusercontent.com/103979308/194798961-320d0be7-d2fc-403d-90d0-65dc8c14192c.png)

因此想询问一下fMSE的统一的计算方式应该是如何的呢
如有回复 非常感谢！

**Comment by xinyuanLLLLL** [comment]
你好，感谢对这一任务的关注！关于这个问题，原因在于这个地方的mask其实并非一个离散的值（仅有0，1），而是一个连续的值（由resize得来），在前景与后景的边界上就会有0-1之间的连续值（如0.5）。而事实上在https://github.com/bcmi/Video-Harmonization-Dataset-HYouTube/blob/01954496b7652d98d4c42dec3eaa9bd08406f0c4/CO2Net/iharm/model/base/ssam_video_lut_dbp.py#L98
我们已经对输出图片做了有关mask的处理，因此不需要在外部再进行重复的计算。

**Comment by RickyLLu** [comment]
你好，感谢对这一任务的关注！关于这个问题，原因在于这个地方的mask其实并非一个离散的值（仅有0，1），而是一个连续的值（由resize得来），在前景与后景的边界上就会有0-1之间的连续值（如0.5）。而事实上在https://github.com/bcmi/Video-Harmonization-Dataset-HYouTube/blob/01954496b7652d98d4c42dec3eaa9bd08406f0c4/CO2Net/iharm/model/base/ssam_video_lut_dbp.py#L98
我们已经对输出图片做了有关mask的处理，因此不需要在外部再进行重复的计算。
