### ISSUE TITLE
The corresponded model of issam_final.pth

### ISSUE THREAD

**Issue by llitmus** [bcmi/Video-Harmonization-Dataset-HYouTube#5]
I search throughout the whole coda, but still find the model. So which one is the corresponded? Thanks a lot!

**Comment by ustcnewly** [comment]
https://github.com/bcmi/Video-Harmonization-Dataset-HYouTube/tree/master/CO2Net/final_models

**Comment by syt0321** [comment]
thanks for replying, but I wonder where I can find the structure of "CO2Net"? the ".pth" is dict format.

**Comment by syt0321** [comment]
> https://github.com/bcmi/Video-Harmonization-Dataset-HYouTube/tree/master/CO2Net/final_models

就是我想复现这个网络，但是找不到网络结构，final_models中的文件只有网络的参数。请问网络结构是哪一个呢？谢谢！
