### ISSUE TITLE
Maybe a mistake in the train command

### ISSUE THREAD

**Issue by Jinec98** [bcmi/Video-Harmonization-Dataset-HYouTube#6]
Hi there,

I found a mistake in the command when I wanted to train the model.

Here is the original command shown in the Readme document:
```
python3  scripts/my_train.py --gpu=1 --dataset_path <Your path to HYouTube> --train_list ./train_list.txt --val_list ./test_frames.txt --backbone <Your backbone model> --backbone_type <Your backbone type, we provide 'issam' and 'rain' here> --previous_num 8 --future_num 8 --use_feature --normalize_inside --exp_name <exp name>
``` 

The arg '--train_list' here is './train_list.txt'. However, in the 'train_list.txt' the paths are stopped at 'objext_x' rather than the images. Regarding the code in './ifarm/data/compose.py', the path must refer to the image, i.e., the frames. Therefore, I think the arg of '--train_list' could be './train_frames.txt'.

Am I right?

Many thanks.

**Comment by RickyLLu** [comment]
Sorry for late reply. Yes. That's an error here. We should use train_frames.txt. Thanks for your suggestion.
