### ISSUE TITLE
broken link for bcmi cloud?

### ISSUE THREAD

**Issue by JEONG8652** [bcmi/Video-Harmonization-Dataset-HYouTube#7]
thank you for your impressive work.

I am trying to download HYouTube dataset.
I'm from outside china so I am trying to download the dataset from BCMI cloud but it looks like bcmi cloud is not working
I have downloaded iHarmony4 dataset a week ago, but iHarmony4 link is not working either now

can you please upload the dataset on an alternative cloud?

**Comment by ustcnewly** [comment]
We have provided the OneDrive link.
